---

- hosts: all
  become: yes
  tasks:
    - name: Create required directory
      file:
        path: "/opt/backup"
        state: directory
    - name: populate required file
      copy:
        dest: /opt/backup/streams
        content: |
               {{ streams }}
